// react-dashboard/src/App.jsx
import { useMemo, useState } from "react";
import "./App.css";

const initialTasks = [
  {
    id: 1,
    title: "Write methodology chapter",
    description:
      "Prepare research design, data collection, evaluation strategy, and ethical considerations.",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-08-05",
    aiGenerated: true
  },
  {
    id: 2,
    title: "Build React prototype",
    description: "Implement the AI-enhanced task dashboard using React.",
    priority: "Medium",
    status: "Pending",
    dueDate: "2026-08-08",
    aiGenerated: false
  },
  {
    id: 3,
    title: "Design recommendation model",
    description:
      "Create weighted scoring and rule-based explanation for framework selection.",
    priority: "High",
    status: "Completed",
    dueDate: "2026-08-10",
    aiGenerated: false
  }
];

function App() {
  const [tasks, setTasks] = useState(initialTasks);

  const [form, setForm] = useState({
    title: "",
    description: "",
    priority: "Medium",
    status: "Pending",
    dueDate: ""
  });

  const [search, setSearch] = useState("");
  const [filterStatus, setFilterStatus] = useState("All");
  const [sortBy, setSortBy] = useState("title");
  const [editingId, setEditingId] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [message, setMessage] = useState("");

  const filteredTasks = useMemo(() => {
    return tasks
      .filter((task) => {
        const matchesSearch = task.title
          .toLowerCase()
          .includes(search.toLowerCase());

        const matchesStatus =
          filterStatus === "All" || task.status === filterStatus;

        return matchesSearch && matchesStatus;
      })
      .sort((a, b) => {
        if (sortBy === "dueDate") {
          return a.dueDate.localeCompare(b.dueDate);
        }

        if (sortBy === "priority") {
          return a.priority.localeCompare(b.priority);
        }

        return a.title.localeCompare(b.title);
      });
  }, [tasks, search, filterStatus, sortBy]);

  const totalTasks = tasks.length;
  const completedTasks = tasks.filter(
    (task) => task.status === "Completed"
  ).length;
  const pendingTasks = tasks.filter((task) => task.status === "Pending").length;
  const aiTasks = tasks.filter((task) => task.aiGenerated).length;

  function handleChange(event) {
    const { name, value } = event.target;
    setForm((previous) => ({
      ...previous,
      [name]: value
    }));
  }

  function resetForm() {
    setForm({
      title: "",
      description: "",
      priority: "Medium",
      status: "Pending",
      dueDate: ""
    });

    setEditingId(null);
  }

  function handleSubmit(event) {
    event.preventDefault();

    if (!form.title.trim()) {
      setMessage("Task title is required.");
      return;
    }

    if (!form.dueDate) {
      setMessage("Due date is required.");
      return;
    }

    if (editingId) {
      setTasks((previous) =>
        previous.map((task) =>
          task.id === editingId
            ? {
                ...task,
                ...form,
                aiGenerated: form.description.trim().length > 0
              }
            : task
        )
      );

      setMessage("Task updated successfully.");
    } else {
      const newTask = {
        id: Date.now(),
        ...form,
        aiGenerated: form.description.trim().length > 0
      };

      setTasks((previous) => [newTask, ...previous]);
      setMessage("Task created successfully.");
    }

    resetForm();
  }

  function handleEdit(task) {
    setEditingId(task.id);

    setForm({
      title: task.title,
      description: task.description,
      priority: task.priority,
      status: task.status,
      dueDate: task.dueDate
    });

    setMessage("Editing selected task.");
  }

  function handleDelete(id) {
    setTasks((previous) => previous.filter((task) => task.id !== id));
    setMessage("Task deleted successfully.");
  }

  function generateDescription() {
    if (!form.title.trim()) {
      setMessage("Enter a task title before generating AI description.");
      return;
    }

    setAiLoading(true);
    setMessage("Generating AI description...");

    setTimeout(() => {
      const aiDescription = `This task involves completing "${form.title}" by planning the work, identifying key requirements, carrying out the implementation, and reviewing the final outcome.`;

      setForm((previous) => ({
        ...previous,
        description: aiDescription
      }));

      setAiLoading(false);
      setMessage("AI description generated successfully.");
    }, 900);
  }

  return (
    <div className="app">
      <aside className="sidebar">
        <h2>TaskFlow AI</h2>
        <p>React Prototype</p>

        <nav>
          <a href="#dashboard">Dashboard</a>
          <a href="#tasks">Tasks</a>
          <a href="#recommendation">Recommendation Model</a>
        </nav>
      </aside>

      <main className="main">
        <section id="dashboard" className="hero">
          <div>
            <h1>AI-Enhanced Task Management Dashboard</h1>
            <p>
              React implementation for evaluating framework suitability and AI
              integration complexity.
            </p>
          </div>

          <span className="tag">Dissertation Prototype</span>
        </section>

        <section className="stats-grid">
          <div className="card stat-card">
            <span>Total Tasks</span>
            <strong>{totalTasks}</strong>
          </div>

          <div className="card stat-card">
            <span>Completed</span>
            <strong>{completedTasks}</strong>
          </div>

          <div className="card stat-card">
            <span>Pending</span>
            <strong>{pendingTasks}</strong>
          </div>

          <div className="card stat-card">
            <span>AI Generated</span>
            <strong>{aiTasks}</strong>
          </div>
        </section>

        <section className="layout">
          <form className="card form-card" onSubmit={handleSubmit}>
            <h2>{editingId ? "Edit Task" : "Create Task"}</h2>

            {message && <p className="message">{message}</p>}

            <label>Task Title</label>
            <input
              name="title"
              value={form.title}
              onChange={handleChange}
              placeholder="Example: Prepare dissertation implementation chapter"
            />

            <button
              type="button"
              className="ai-button"
              onClick={generateDescription}
            >
              {aiLoading ? "Generating..." : "Generate AI Description"}
            </button>

            <label>Description</label>
            <textarea
              name="description"
              value={form.description}
              onChange={handleChange}
              placeholder="AI-generated or manually written description"
            />

            <div className="row">
              <div>
                <label>Priority</label>
                <select
                  name="priority"
                  value={form.priority}
                  onChange={handleChange}
                >
                  <option>High</option>
                  <option>Medium</option>
                  <option>Low</option>
                </select>
              </div>

              <div>
                <label>Status</label>
                <select
                  name="status"
                  value={form.status}
                  onChange={handleChange}
                >
                  <option>Pending</option>
                  <option>In Progress</option>
                  <option>Completed</option>
                </select>
              </div>
            </div>

            <label>Due Date</label>
            <input
              type="date"
              name="dueDate"
              value={form.dueDate}
              onChange={handleChange}
            />

            <div className="actions">
              <button type="submit">
                {editingId ? "Update Task" : "Save Task"}
              </button>

              <button type="button" className="secondary" onClick={resetForm}>
                Clear
              </button>
            </div>
          </form>

          <section id="tasks" className="card">
            <h2>Task List</h2>

            <div className="controls">
              <input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Search tasks..."
              />

              <select
                value={filterStatus}
                onChange={(event) => setFilterStatus(event.target.value)}
              >
                <option>All</option>
                <option>Pending</option>
                <option>In Progress</option>
                <option>Completed</option>
              </select>

              <select
                value={sortBy}
                onChange={(event) => setSortBy(event.target.value)}
              >
                <option value="title">Sort by title</option>
                <option value="dueDate">Sort by due date</option>
                <option value="priority">Sort by priority</option>
              </select>
            </div>

            {filteredTasks.map((task) => (
              <article className="task" key={task.id}>
                <div>
                  <h3>{task.title}</h3>
                  <p>{task.description}</p>

                  <div className="badges">
                    <span>{task.priority}</span>
                    <span>{task.status}</span>
                    {task.aiGenerated && <span>AI Description</span>}
                  </div>
                </div>

                <div className="task-actions">
                  <button onClick={() => handleEdit(task)}>Edit</button>
                  <button
                    className="danger"
                    onClick={() => handleDelete(task.id)}
                  >
                    Delete
                  </button>
                </div>
              </article>
            ))}
          </section>
        </section>

        <section id="recommendation" className="card recommendation">
          <h2>Framework Recommendation Model Preview</h2>

          <p>
            This part will later use evaluation evidence from React, Angular,
            and Vue.js to recommend the most suitable framework based on project
            requirements.
          </p>

          <div className="score">
            <span>Angular</span>
            <div>
              <strong style={{ width: "84%" }}></strong>
            </div>
            <b>84%</b>
          </div>

          <div className="score">
            <span>React</span>
            <div>
              <strong style={{ width: "76%" }}></strong>
            </div>
            <b>76%</b>
          </div>

          <div className="score">
            <span>Vue.js</span>
            <div>
              <strong style={{ width: "71%" }}></strong>
            </div>
            <b>71%</b>
          </div>

          <p className="explanation">
            Example explanation: Angular is recommended where maintainability,
            scalability, security, and structured development are high
            priorities.
          </p>
        </section>
      </main>
    </div>
  );
}

export default App;

// angular-dashboard/src/app/app.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit } from "@angular/core";
import { FormsModule } from "@angular/forms";

type UserRole = "Admin" | "User";
type TaskPriority = "High" | "Medium" | "Low";
type TaskStatus = "Pending" | "In Progress" | "Completed";
type ActivePage = "dashboard" | "tasks" | "recommendation" | "admin";

interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  role: UserRole;
}

interface Task {
  id: number;
  ownerEmail: string;
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
  aiGenerated: boolean;
}

interface TaskForm {
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
}

const INITIAL_USERS: User[] = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@gmail.com",
    password: "admin123",
    role: "Admin"
  },
  {
    id: 2,
    name: "Dhirendra Thakur",
    email: "dhiren@gmail.com",
    password: "dhiren123",
    role: "User"
  }
];

const INITIAL_TASKS: Task[] = [
  {
    id: 1,
    ownerEmail: "dhiren@gmail.com",
    title: "Write methodology chapter",
    description:
      "Prepare research design, data collection, evaluation strategy, and ethical considerations.",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-08-05",
    aiGenerated: true
  },
  {
    id: 2,
    ownerEmail: "dhiren@gmail.com",
    title: "Build Angular prototype",
    description:
      "Implement the AI-enhanced task dashboard using Angular with the same functional requirements as React.",
    priority: "Medium",
    status: "Pending",
    dueDate: "2026-08-08",
    aiGenerated: false
  },
  {
    id: 3,
    ownerEmail: "admin@gmail.com",
    title: "Design recommendation model",
    description:
      "Create weighted scoring and rule-based explanation for framework selection.",
    priority: "High",
    status: "Completed",
    dueDate: "2026-08-10",
    aiGenerated: false
  }
];

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: "./app.html",
  styleUrl: "./app.css"
})
export class App implements OnInit {
  users: User[] = [];
  tasks: Task[] = [];
  currentUser: User | null = null;

  authMode: "login" | "register" = "login";
  activePage: ActivePage = "dashboard";

  loginForm = {
    email: "",
    password: ""
  };

  registerForm: Omit<User, "id"> = {
    name: "",
    email: "",
    password: "",
    role: "User"
  };

  taskForm: TaskForm = {
    title: "",
    description: "",
    priority: "Medium",
    status: "Pending",
    dueDate: ""
  };

  search = "";
  filterStatus: "All" | TaskStatus = "All";
  sortBy: "title" | "dueDate" | "priority" = "title";

  editingTaskId: number | null = null;
  message = "";
  authMessage = "";
  aiLoading = false;

  ngOnInit(): void {
    this.users = this.loadFromStorage<User[]>(
      "angular_taskflow_users",
      INITIAL_USERS
    );

    this.tasks = this.loadFromStorage<Task[]>(
      "angular_taskflow_tasks",
      INITIAL_TASKS
    );

    this.currentUser = this.loadFromStorage<User | null>(
      "angular_taskflow_current_user",
      null
    );

    if (this.currentUser) {
      this.activePage = this.currentUser.role === "Admin" ? "admin" : "dashboard";
    }
  }

  loadFromStorage<T>(key: string, fallback: T): T {
    const storedValue = localStorage.getItem(key);

    if (!storedValue) {
      return fallback;
    }

    try {
      return JSON.parse(storedValue) as T;
    } catch {
      return fallback;
    }
  }

  saveUsers(): void {
    localStorage.setItem("angular_taskflow_users", JSON.stringify(this.users));
  }

  saveTasks(): void {
    localStorage.setItem("angular_taskflow_tasks", JSON.stringify(this.tasks));
  }

  saveCurrentUser(): void {
    if (this.currentUser) {
      localStorage.setItem(
        "angular_taskflow_current_user",
        JSON.stringify(this.currentUser)
      );
    } else {
      localStorage.removeItem("angular_taskflow_current_user");
    }
  }

  setAuthMode(mode: "login" | "register"): void {
    this.authMode = mode;
    this.authMessage = "";
  }

  login(): void {
    const foundUser = this.users.find(
      (user) =>
        user.email === this.loginForm.email &&
        user.password === this.loginForm.password
    );

    if (!foundUser) {
      this.authMessage = "Invalid email or password.";
      return;
    }

    this.currentUser = foundUser;
    this.saveCurrentUser();

    this.activePage = foundUser.role === "Admin" ? "admin" : "dashboard";
    this.authMessage = "";
  }

  register(): void {
    if (
      !this.registerForm.name.trim() ||
      !this.registerForm.email.trim() ||
      !this.registerForm.password.trim()
    ) {
      this.authMessage = "All registration fields are required.";
      return;
    }

    const emailExists = this.users.some(
      (user) => user.email === this.registerForm.email
    );

    if (emailExists) {
      this.authMessage = "This email is already registered.";
      return;
    }

    const newUser: User = {
      id: Date.now(),
      ...this.registerForm
    };

    this.users = [...this.users, newUser];
    this.saveUsers();

    this.registerForm = {
      name: "",
      email: "",
      password: "",
      role: "User"
    };

    this.authMessage = "Registration successful. Please login.";
    this.authMode = "login";
  }

  logout(): void {
    this.currentUser = null;
    this.loginForm = {
      email: "",
      password: ""
    };
    this.saveCurrentUser();
    this.authMode = "login";
  }

  setActivePage(page: ActivePage): void {
    this.activePage = page;
    this.message = "";
  }

  get visibleTasks(): Task[] {
    if (!this.currentUser) {
      return [];
    }

    if (this.currentUser.role === "Admin") {
      return this.tasks;
    }

    return this.tasks.filter(
      (task) => task.ownerEmail === this.currentUser?.email
    );
  }

  get filteredTasks(): Task[] {
    return [...this.visibleTasks]
      .filter((task) => {
        const matchesSearch = task.title
          .toLowerCase()
          .includes(this.search.toLowerCase());

        const matchesStatus =
          this.filterStatus === "All" || task.status === this.filterStatus;

        return matchesSearch && matchesStatus;
      })
      .sort((a, b) => {
        if (this.sortBy === "dueDate") {
          return (a.dueDate || "").localeCompare(b.dueDate || "");
        }

        if (this.sortBy === "priority") {
          return a.priority.localeCompare(b.priority);
        }

        return a.title.localeCompare(b.title);
      });
  }

  get totalTasks(): number {
    return this.visibleTasks.length;
  }

  get completedTasks(): number {
    return this.visibleTasks.filter((task) => task.status === "Completed")
      .length;
  }

  get pendingTasks(): number {
    return this.visibleTasks.filter((task) => task.status === "Pending").length;
  }

  get inProgressTasks(): number {
    return this.visibleTasks.filter((task) => task.status === "In Progress")
      .length;
  }

  get aiTasks(): number {
    return this.visibleTasks.filter((task) => task.aiGenerated).length;
  }

  get highPriorityTasks(): number {
    return this.visibleTasks.filter((task) => task.priority === "High").length;
  }

  get completionRate(): number {
    if (this.totalTasks === 0) {
      return 0;
    }

    return Math.round((this.completedTasks / this.totalTasks) * 100);
  }

  get adminUsers(): number {
    return this.users.filter((user) => user.role === "Admin").length;
  }

  get normalUsers(): number {
    return this.users.filter((user) => user.role === "User").length;
  }

  resetTaskForm(): void {
    this.taskForm = {
      title: "",
      description: "",
      priority: "Medium",
      status: "Pending",
      dueDate: ""
    };

    this.editingTaskId = null;
  }

  saveTask(): void {
    if (!this.currentUser) {
      return;
    }

    if (!this.taskForm.title.trim()) {
      this.message = "Task title is required.";
      return;
    }

    if (!this.taskForm.dueDate) {
      this.message = "Due date is required.";
      return;
    }

    if (this.editingTaskId) {
      this.tasks = this.tasks.map((task) =>
        task.id === this.editingTaskId
          ? {
              ...task,
              ...this.taskForm,
              ownerEmail: task.ownerEmail || this.currentUser?.email || "",
              aiGenerated: this.taskForm.description.trim().length > 0
            }
          : task
      );

      this.message = "Task updated successfully.";
    } else {
      const newTask: Task = {
        id: Date.now(),
        ownerEmail: this.currentUser.email,
        ...this.taskForm,
        aiGenerated: this.taskForm.description.trim().length > 0
      };

      this.tasks = [newTask, ...this.tasks];
      this.message = "Task created successfully.";
    }

    this.saveTasks();
    this.resetTaskForm();
  }

  editTask(task: Task): void {
    if (
      this.currentUser?.role !== "Admin" &&
      task.ownerEmail !== this.currentUser?.email
    ) {
      this.message = "You can only edit your own tasks.";
      return;
    }

    this.editingTaskId = task.id;

    this.taskForm = {
      title: task.title,
      description: task.description,
      priority: task.priority,
      status: task.status,
      dueDate: task.dueDate
    };

    this.message = "Editing selected task.";
  }

  deleteTask(taskId: number): void {
    const selectedTask = this.tasks.find((task) => task.id === taskId);

    if (
      selectedTask &&
      this.currentUser?.role !== "Admin" &&
      selectedTask.ownerEmail !== this.currentUser?.email
    ) {
      this.message = "You can only delete your own tasks.";
      return;
    }

    this.tasks = this.tasks.filter((task) => task.id !== taskId);
    this.saveTasks();
    this.message = "Task deleted successfully.";
  }

  async generateDescription(): Promise<void> {
    if (!this.taskForm.title.trim()) {
      this.message = "Enter a task title before generating AI description.";
      return;
    }

    this.aiLoading = true;
    this.message = "Generating professional AI task description...";

    try {
      const response = await fetch(
        "http://localhost:5000/api/ai/generate-task-description",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            title: this.taskForm.title,
            priority: this.taskForm.priority,
            status: this.taskForm.status,
            dueDate: this.taskForm.dueDate,
            projectContext:
              "MSc dissertation project involving React, Angular, Vue.js, AI-enhanced task dashboard, secure backend API integration, and intelligent framework recommendation model."
          })
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "AI generation failed.");
      }

      this.taskForm.description = data.description;
      this.message = "Professional AI description generated successfully.";
    } catch (error) {
      this.message =
        error instanceof Error
          ? error.message
          : "Unable to connect to the AI backend. Please check that the backend server is running.";
    } finally {
      this.aiLoading = false;
    }
  }

  trackByTaskId(index: number, task: Task): number {
    return task.id;
  }

  trackByUserId(index: number, user: User): number {
    return user.id;
  }
}
