// react-dashboard/src/pages/RegisterPage.jsx
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";

function RegisterPage({ users, setUsers }) {
  const navigate = useNavigate();

  const [registerForm, setRegisterForm] = useState({
    name: "",
    email: "",
    password: "",
    role: "User"
  });

  const [message, setMessage] = useState("");

  function handleChange(event) {
    const { name, value } = event.target;

    setRegisterForm((previous) => ({
      ...previous,
      [name]: value
    }));
  }

  function handleRegister(event) {
    event.preventDefault();

    if (
      !registerForm.name.trim() ||
      !registerForm.email.trim() ||
      !registerForm.password.trim()
    ) {
      setMessage("All registration fields are required.");
      return;
    }

    const emailExists = users.some((user) => user.email === registerForm.email);

    if (emailExists) {
      setMessage("This email is already registered.");
      return;
    }

    const newUser = {
      id: Date.now(),
      ...registerForm
    };

    setUsers((previous) => [...previous, newUser]);
    navigate("/login");
  }

  return (
    <div className="auth-page">
      <div className="auth-left">
        <span className="section-label">Create account</span>
        <h1>Register</h1>

        <p>
          The register page is separated from the login page to create a cleaner
          and more professional React project structure.
        </p>

        <div className="auth-highlight">
          <strong>Research relevance</strong>

          <p>
            Registration supports evaluation of form validation, state handling,
            user roles, and future backend authentication integration.
          </p>
        </div>
      </div>

      <div className="auth-card">
        <form onSubmit={handleRegister}>
          <h2>Create Account</h2>

          <p className="auth-subtitle">
            Create a prototype account for the dashboard.
          </p>

          {message && <p className="message">{message}</p>}

          <label>Full Name</label>
          <input
            name="name"
            value={registerForm.name}
            onChange={handleChange}
            placeholder="Enter full name"
          />

          <label>Email</label>
          <input
            name="email"
            value={registerForm.email}
            onChange={handleChange}
            placeholder="Enter email address"
          />

          <label>Password</label>
          <input
            type="password"
            name="password"
            value={registerForm.password}
            onChange={handleChange}
            placeholder="Create password"
          />

          <label>Role</label>
          <select
            name="role"
            value={registerForm.role}
            onChange={handleChange}
          >
            <option>User</option>
            <option>Admin</option>
          </select>

          <button type="submit">Create Account</button>

          <p className="switch-auth">
            Already have an account? <Link to="/login">Login</Link>
          </p>
        </form>
      </div>
    </div>
  );
}

export default RegisterPage;

// vue-dashboard/src/pages/RegisterPage.vue
<template>
  <div class="auth-page">
    <div class="auth-left">
      <span class="section-label">Create account</span>
      <h1>Register</h1>

      <p>
        The register page is separated from the login page to create a cleaner
        and more professional Vue.js project structure.
      </p>

      <div class="auth-highlight">
        <strong>Research relevance</strong>
        <p>
          Registration supports evaluation of form validation, state handling,
          user roles, and future backend authentication integration.
        </p>
      </div>
    </div>

    <div class="auth-card">
      <form @submit.prevent="handleRegister">
        <h2>Create Account</h2>

        <p class="auth-subtitle">
          Create a prototype account for dashboard access.
        </p>

        <p v-if="message" class="message">{{ message }}</p>

        <label>Full Name</label>
        <input v-model="name" placeholder="Enter full name" />

        <label>Email</label>
        <input v-model="email" placeholder="Enter email address" />

        <label>Password</label>
        <input v-model="password" type="password" placeholder="Create password" />

        <label>Role</label>
        <select v-model="role">
          <option>User</option>
          <option>Admin</option>
        </select>

        <button type="submit">Create Account</button>

        <p class="switch-auth">
          Already have an account?
          <RouterLink to="/login">Login</RouterLink>
        </p>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import authService from "../services/authService";

const router = useRouter();

const name = ref("");
const email = ref("");
const password = ref("");
const role = ref("User");
const message = ref("");

function handleRegister() {
  if (!name.value.trim() || !email.value.trim() || !password.value.trim()) {
    message.value = "All registration fields are required.";
    return;
  }

  const result = authService.register({
    name: name.value,
    email: email.value,
    password: password.value,
    role: role.value
  });

  if (!result.success) {
    message.value = result.message;
    return;
  }

  router.push("/login");
}
</script>
